### ISSUE TITLE
Doesn't work with NodeMCU esp8266

### ISSUE THREAD

**Issue by jackypea** [realmrvodka/n2d#11]
This programme doesn't seem to find my NodeMCU . 

Is there a solution to this.

many thanks, jack

**Comment by ghost** [comment]
Can you please describe the issue in a bit more detail? If the program is stuck on the 'waiting' phase then your computer has not detected the device or N2D is unable to access it.

**Comment by ghost** [comment]
I've closed this issue due to inactivity. If you need further help open another issue.
