### ISSUE TITLE
Brilliant project, just quick question.

### ISSUE THREAD

**Issue by earlcharles1** [realmrvodka/n2d#12]
After I setup the program and it's ready to be used, which default network do I connect to and what's the password for it?

**Comment by ghost** [comment]
Hi there. First of all N2D does not require setup to be used as it's a stand alone executable. Once the program completes flashing the ESP8266 reset the device by pressing the RST button, if available and connect to the network named **pwned** with the password **deauther.**

**Comment by earlcharles1** [comment]
You're great, thank you.
