### ISSUE TITLE
device false

### ISSUE THREAD

**Issue by Supadad** [realmrvodka/n2d#13]

**Comment by AdamG774** [comment]
Maybe tell him what happend retard

**Comment by ghost** [comment]
Can you please elaborate on your issue. '_Device False_' does not tell me what went wrong. If the program is not detecting your device make sure you have correct drivers installed and that you are using a compatible device. If still not working, why not try and download the source and modify it yourself or use another tool. If you **do not** respond within **48** hours, I'm closing this issue.

**Comment by Supadad** [comment]
Sorry! Wrong move on my part.My device shows no function. It appears to be broken. I wanted search results.
Please close this request.
