### ISSUE TITLE
Possibility to select the BIN

### ISSUE THREAD

**Issue by Cyb3rn0id** [realmrvodka/n2d#20]
The tool connects to repository and downloads a generic version.
I need a specific version to be uploaded on the Deauther Watch by DSTike, the downloaded version does not support the oled display

**Comment by ghost** [comment]
Unfortunately, there's nothing you can do but use another tool. I might make an updated release for when v3 comes out, but until then you're going to have to find another way or wait. Sorry about that, good luck.
