### ISSUE TITLE
Led screen still wont light up

### ISSUE THREAD

**Issue by Zentriex** [realmrvodka/n2d#21]
I tried reflashing twice. Made sure the led tape was still connected all the way. The watch is charged. the orange light is lighting up on the side but the LED screen wont load in

**Comment by ghost** [comment]
Hey @anonplaguedoctor, this application is designed for the default NodeMCU / D1 Mini Config. This is why you are facing this problem. Please use an alternative flash tool or wait for an update as soon as Deauther v3 is released.
