### ISSUE TITLE
Flashed wrong device?

### ISSUE THREAD

**Issue by Nipeno** [realmrvodka/n2d#22]
I just ran the program without having my board plugged in and it still said it found something and apparently started flashing it,
now I am concerned as to what it flashed or tried flashing.
Please help, I don't think it's supposed to do this.

**Comment by ghost** [comment]
Yeah. I'm aware of that problem with some users, **don't worry** though! It didn't flash anything as the program isn't capable of doing that anyway. If it did run esptool.py, nothing would've been flashed as that tool would not be able to connect to the 'esp8266'. I am considering working on another tool upon deauther v3's launch. As for now, if it isn't working, download esptool.py manually and follow Spacehuhn's instructions (they are quite simple!)

Edit: I'm working on a new version of the tool. It should be live within a week or two!
