### ISSUE TITLE
Mod 

### ISSUE THREAD

**Issue by KatzeMau** [realmrvodka/n2d#24]
How can i mod it that it works for https://github.com/samdenty/Wi-PWN ?

**Comment by ghost** [comment]
You can change the source code to download from a different source or if you know how to use a debugger, you can break the program after it downloads, replace the file and resume execution.

**Comment by KatzeMau** [comment]
Is it okay if I fork it?
and upload a version for the WI-PWN

**Comment by ghost** [comment]
Of course! Provided you follow the guidelines of this license: https://mit-license.org/
