### ISSUE TITLE
Small error in the URL

### ISSUE THREAD

**Issue by scheibleit** [realmrvodka/n2d#28]
Super tool - has worked great. In the _readme.md_ I came across a small error. In the first sentence where the here is linked, the link is missing an "n". This will cause a 404 error. 
"Get the latest version **here**. Our Wiki is useful for troubleshooting and program help."
https://github.com/pseudo8086/2d/releases > https://github.com/pseudo8086/n2d/releases

**Comment by octolance** [comment]
Oh my! That's an embarrassing mistake to make, thanks for letting me know. :joy:
