### ISSUE TITLE
Flashed wrong image

### ISSUE THREAD

**Issue by DerKiLLa** [realmrvodka/n2d#3]
Hi! I've a WiFi Deauther OLED V3.5 and tried to flash the new firmware (2.1.0) with your tool. It flashed with success, but after it, my OLED wasnt working anymore.

I looked at the downloaded bin-File and saw, it is 693kb. I downloaded the newest image from spacehuhn (deauther_2.1.0_DSTIKE_OLED_v3.5_v4_Monster.bin) and saw, it is 694kb. I just overwrite your deauther_2.1.0_1mb.bin with mine and made it readonly. Flashed again with an error-message, that the application cant access the bin, but it worked and now my OLED is working again :)

**Comment by ghost** [comment]
Glad to hear it's working, and the access error probably means that it can't open the file in read-write mode, only read. I'll update the tool to allow custom bin files. 
**mrvodka007**
