### ISSUE TITLE
Is the N2DX firmware going to be re-released ?

### ISSUE THREAD

**Issue by FaisalAhmed123** [realmrvodka/n2d#31]
Is the N2DX firmware going to be re-released ?

**Comment by octolance** [comment]
Could you please clarify what you mean by firmware? N2DX was a test application I created a few years ago, it was more of a user-interface experiment than anything useful. It wasn't actual firmware to be flashed to an ESP8266.

**Comment by FaisalAhmed123** [comment]
> Could you please clarify what you mean by firmware? N2DX was a test application I created a few years ago, it was more of a user-interface experiment than anything useful. It wasn't actual firmware to be flashed to an ESP8266.

The N2DX version made it a lot easier to flash the firmware, however it seems to have been deleted by the author, the only trace of it I can find is on this website, can't find it anywhere else anymore

https://blog.connectinut.co.uk/2021/02/20/kick-anyone-out-of-their-own-wifi-without-their-password-esp8266-deauther/

**Comment by octolance** [comment]
ND2X is no longer maintained and is quite out of date, plus like I said it wasn't designed to be for widespread use but rather a test program. I find it very interesting that you say N2DX was easier to use; if you've got any feedback regarding N2D22, that would be appreciated so it can be improved.
