### ISSUE TITLE
Not recognising a NodeMCU with CH340G

### ISSUE THREAD

**Issue by fengshuo2004** [realmrvodka/n2d#5]
NodeMCU | Specs
------ | ------
Wifi module | ESP8266
UART chip | CH340G

1. I have the correct driver installed

2. Windows recognises my NodeMCU as I plug it in (hear the "device connected" sound as well as `USB SERIAL CH340 (COM4)` pops up in device manager under *Ports (COM & LPT)*) See screenshot below:

![Device Manager](https://i.imgur.com/LFWRzSI.png)

Whilst all this is happening, N2D is still *Looking for an ESP8266...*

I tried:

- Unplug and replug

- Rerun N2D as administrator

- Reinstall driver using N2D's *Install Driver* button and then restarting computer

Of which none solved the problem, please help.

**Comment by ghost** [comment]
Hmmm. That is a bit odd. Try using n2dx. That's the new and improved version. 
https://github.com/mrvodka007/n2dx

**Comment by misterboe** [comment]
same here
