### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by ctaylor1985** [realmrvodka/n2d#8]
hi again, how do i connect to http://192.168.4.1 it will not let me, thanks carl

**Comment by ghost** [comment]
Unfortunately I am unable to assist you with problems connecting to the Web interface. **Here's what you can try:**

- Disabling mobile data (on mobile devices)
- Unplugging the ethernet cable (on desktop and laptop computers)
- Restarting the device after flashing

If nothing works, open another issue and provide me with details such as the _device you are flashing_, the _device you are attempting to connect on_ and more **if necessary**.
