### ISSUE TITLE
looks like virus in this file

### ISSUE THREAD

**Issue by 404notfound-3** [realmrvodka/n2d#9]
[https://www.virustotal.com/gui/file/3fcb467a225e21895da162a4822cb6aca442f4ee18dacc7d5310f3045ecf0cd0/detection](url)

**Comment by mrvodka007** [comment]
The detection ratio is 3/70 and you want to tell me this is a virus. Look through the source code and tell me if you can spot anything suspicious before commenting such rubbish again. 🤨
